ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 0 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Traceback (most recent call last):
  File "/home/s1045064/dissertation/repo-diss/sentence-classification/three.py", line 14, in <module>
    import theano
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 29, in test_nvidia_driver1
    A = cuda.shared_constructor(a)
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/sandbox/cuda/var.py", line 218, in float32_shared_constructor
    enable_cuda=False)
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 557, in use
    gpu_init(use.device_number, config.lib.cnmem)
RuntimeError: ('initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1\n', 'You asked to force this device and it failed. No fallback to the cpu or other gpu device.')
